export const initDataOfMeasureSheet = {
  no: 0,
  room: "",
  style: "",
  roWidth: "",
  roHeight: "",
  orderWidth: "",
  orderHeight: "",
  grids: "",
  intColor: "",
  extColor: "",
  foam: "",
  temp: "",
  obsc: "",
  energy: "",
  mullCuts: "",
  notes: "",
};

export const initDataOfWindowOrder = {
  no: 0,
  qty: 0,
  type: "",
  series: "",
  foamFrame: "",
  frame: "",
  szWidth: "",
  szX: "",
  szHeigh: "",
  split: "",
  intColor: "",
  extColor: "",
  screenHalf: "",
  screenFull: "",
  screenFlex: "",
  gridsFlat: "",
  gridsSculp: "",
  gridsSDL: "",
  pattern: "",
  blinds: "",
  clear: "",
  szone: "",
  elite: "",
  sunshld: "",
  argon: "",
  stc: "",
  impact: "",
  obsc: "",
  rain: "",
  temp: "",
  casementL: "",
  casementR: "",
  casementPW: "",
  mullFLD: "",
  mullFAC: "",
  comment: "",
};

export const initDataOfCommisionForm = {
  store: "",
  data: "",
  salesConsultant: "",
  sales: "",
  customerName: "",
  comm: "",
  wwOrder: "",
  calculation: "",
  contractPrice: "",
  bonus: "",
};

export const typeOfCheckBox = {
  WindowTable: "WindowTable",
  PatioDoorOrder: "PatioDoorOrder",
};
