export const initDataOfMeasureSheet = {
  no: 0,
  room: '',
  style: '',
  roWidth: '',
  roHeight: '',
  orderWidth: '',
  orderHeight: '',
  grids: '',
  intColor: '',
  extColor: '',
  foam: '',
  temp: '',
  obsc: '',
  energy: '',
  mullCuts: '',
  notes: '',
};

export const initDataOfWindowOrder = {
  qty: 0,
  type: '',
  series: '',
  foam: '',
  nailfin: '',
  szWidth: '',
  szX: '',
  szHeigh: '',
  split: '',
  intColor: '',
  extColor: '',
  grid: '',
  pattern: '',
  blinds: '',
  energy: '',
  obsc: '',
  temp: '',
  casementsL: '',
  casementsR: '',
  casementsPW: '',
  mulls: '',
  comment: '',
};

export const initDataOfCommisionForm = {
  store: '',
  data: '',
  salesConsultant: '',
  sales: '',
  customerName: '',
  comm: '',
  wwOrder: '',
  calculation: '',
  contractPrice: '',
  bonus: '',
};

export const typeOfCheckBox = {
  WindowTable: 'WindowTable',
  PatioDoorOrder: 'PatioDoorOrder',
};
